LibLog/lib_log/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('',include('lib_logs.urls'))
]

LibLog/lib_logs/urls.py
"""Визначаємо URL шаблони для lib_logs"""
from django.urls import path
from . import views

app_name = 'lib_logs'
urlpatterns = [
    # Головна сторінка
    path('', views.index, name='index'),

    # Сторінка, що виводить всі теми.
    path('books/', views.books, name='books'),

    # Сторінка книги
    path('book/<int:book_id>/', views.book, name='book'),

    # Сторінка для додавання нової теми
    path('new_book/', views.new_book, name= 'new_book'),

    # Сторінка для додавання нової теми
    path('new_review/<int:book_id>/', views.new_review, name='new_review'),

    # Сторінка для додавання нової теми
    path('edit_review/<int:review_id>/', views.edit_review, name='edit_review')
]

LibLog/users/urls.py
from django.urls import path, include

app_name = 'users'
urlpatterns = [
    path('',include('django.contrib.auth.urls')),
]

LibLog/lib_logs/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    """Назва книги"""
    text = models.CharField(max_length=200)
    data_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Повернути представлення моделі"""
        return self.text

class Review(models.Model):
    """Відгук на прочитану книгу"""
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'reviews'

    def __str__(self):
        return f"{self.text[:50]}..."

LibLog/users/models.py
from django.db import models

# Create your models here.

LibLog/lib_logs/forms.py
from django import forms
from .models import Book, Review


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['text']
        labels = {'text': ''}


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

LibLog/lib_logs/views.py
from django.shortcuts import render, redirect
from .models import Book, Review
from .forms import BookForm, ReviewForm


# Create your views here.


def index(request):
    """Головна сторінка Журналу бібліотеки"""
    return render(request, 'lib_logs/index.html')


def books(request):
    """Показує всі книги"""
    books = Book.objects.order_by('data_added')
    context = {'books': books}
    return render(request, 'lib_logs/books.html', context)


def book(request, book_id):
    """Показує одну книгу та усі відгуки до неї"""
    book = Book.objects.get(id=book_id)
    reviews = book.review_set.order_by('-date_added')
    context = {'book': book, 'reviews': reviews}
    return render(request, 'lib_logs/book.html', context)

def new_book(request):
    '''Додаємо нову книгу'''
    if request.method != 'POST':
        # Жодних даних невідправлено - створити порожню форму.
        form = BookForm()
    else:
        # відправлений POST; обробити дані
        form = BookForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('lib_logs:books')

    # Показати порожню або недійсну форму.
    context = {'form': form}
    return render(request, 'lib_logs/new_book.html', context)

def new_review(request, book_id):
    '''Додаємо новий відгук до існуючої книги'''
    book=Book.objects.get(id=book_id)
    if request.method != 'POST':
        # Жодних даних невідправлено - створити порожню форму.
        form = ReviewForm()
    else:
        # відправлений POST; обробити дані
        form = ReviewForm(data=request.POST)
        if form.is_valid():
            new_review = form.save(commit=False)
            new_review.book = book
            new_review.save()
            return redirect('lib_logs:books', book_id=book_id)

    # Показати порожню або недійсну форму.
    context = {'book':book, 'form':form}
    return render(request, 'lib_logs/new_book.html', context)

def edit_review(request, review_id):
    review = Review.objects.get(id=review_id)
    book = review.book

    if request.method != 'POST':
        form = ReviewForm(instance=review)
    else:
        form = ReviewForm(instance=review, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('lib_logs:book', book_id=book.id)
    context = {'review': review, 'book': book, 'form': form}
    return render(request, 'lib_logs/edit_review.html', context)

LibLog/users/views.py
from django.shortcuts import render

# Create your views here.

LibLog/lib_logs/templates/lib_logs/base.html
<p>
  <a href="{% url 'lib_logs:index' %}" >Головна сторінка</a> -
  <a href="{% url 'lib_logs:books' %}" >Книги </a> -
  {% if user.is_authenticated %}
      Hello, {{ user.username }}.
  {% else %}
      <a href="{% url 'users:login' %}" > Вхід</a> -
    {% endif %}
</p>

{% block content %} {%endblock content %}

LibLog/lib_logs/templates/lib_logs/book.html
{% extends 'lib_logs/base.html' %}

{% block content %}

    <p> Книга: {{ book }} </p>
    <p> Відгуки:</p>
    <p>
        <a href="{%  url 'lib_logs:new_review' book.id %}" >Додати новий відгук</a>
    </p>

    <ul>
    {% for review in reviews %}
        <li>
            <p>{{ review.date_added|date:'M d, Y' }}</p>
            <p> {{ review.text|linebreaks }}</p>
            <p>
                <a href="{% url 'lib_logs:edit_review' review.id %}" >Редагувати відгук</a>
            </p>
        </li>
        {% empty %}
        <li> Ще немає відгуку по цій книзі.  <li>
    {% endfor %}
    </ul>

{% endblock content%}

LibLog/lib_logs/templates/lib_logs/books.html
{% extends 'lib_logs/base.html' %}

{% block content %}

<p> Книги </p>

<ul>
{% for book in books %}
    <li>
        <a href= "{%  url 'lib_logs:book' book.id %}" >{{ book }} </a>
    </li>
    {% empty %}
    <li> <li>
    {% endfor %}
</ul>

    <a href= "{%  url 'lib_logs:new_book' %}" > Додати нову книгу </a>

{% endblock %}

LibLog/lib_logs/templates/lib_logs/edit_review.html
{% extends 'lib_logs/base.html' %}

{% block content %}
    <p><a href="{% url 'lib_logs:book' book.id %}">{{ book }} </a></p>

    <p> Редагування відгуку: </p>
    <form action="{% url 'lib_logs:edit_review' review.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit" >Зберегти зміни </button>
    </form>
{% endblock content %}

LibLog/lib_logs/templates/lib_logs/index.html
<p>{% extends 'lib_logs\base.html' %}</p>
{% block content %}
 <p>Журнал відгуків дозволить робити нотатки та відгуки на прочитані книжки. Ви можете ділитись з друзями своїми рецензіями.</p>

{% endblock content %}

LibLog/lib_logs/templates/lib_logs/new_book.html
{% extends 'lib_logs/base.html' %}

{% block content %}

    <p> Додавання нової книги </p>
    <form action="{% url 'lib_logs:new_book' %}" method= 'post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Додати книгу </button>
    </form>
{% endblock %}

LibLog/lib_logs/templates/lib_logs/new_review.html
{% extends 'lib_logs/base.html' %}

{% block content %}
    <p><a href="{% url 'lib_logs:book' book.id %}">{{ book }} </a></p>

    <p> Додавання нового відгуку: </p>
    <form action="{% url 'lib_logs:new_review' book.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit" >Додати відгук </button>
    </form>
{% endblock content %}